# Generated by Django 3.2.5 on 2021-08-25 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_curso_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='datainicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 13, 59, 9, 177797, tzinfo=utc)),
        ),
    ]
