# Generated by Django 3.2.5 on 2021-09-08 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_curso_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='datainicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 11, 24, 4, 849639, tzinfo=utc)),
        ),
    ]
